# docker-compose.yml
version: '3.7' # This version refers to the version of the docker-compose file specification.
services:
  webserver:
    build:
      context: .
    ports:
      - 8001:8001
    read_only: true
    tmpfs:
      - /app/static/cached


